---
resources:
- name: code
  type: git
  source:
    uri: https://github.com/cznewt/goarchitect.git
    branch: concourse

- name: daily-build
  type: time
  source:
    interval: 24h

jobs:
- name: test
  public: true
  serial: true
  plan:
  - get: code
    trigger: true
  - get: daily-build
    trigger: true

  - aggregate:
    - task: test-latest
      file: code/concourse/task-golang.yml
    - task: test-1.8
      config:
        platform: linux

        image_resource:
          type: docker-image
          source: {repository: golang, tag: 1.8}

        inputs:
        - name: code
          path: gopath/src/github.com/tomkukral/goarchitect

        run:
          path: sh
          args:
          - -exc
          - |
            export GOPATH=$(pwd)/gopath
            export PATH=$PATH:$(pwd)/gopath/bin/
            env
            find .
            cd gopath/src/github.com/tomkukral/goarchitect/
            ./test.sh
    - task: test-1.9
      config:
        platform: linux

        image_resource:
          type: docker-image
          source: {repository: golang, tag: 1.9}

        inputs:
        - name: code
          path: gopath/src/github.com/tomkukral/goarchitect

        run:
          #dir: gopath/src/github.com/tomkukral/goarchitect/
          path: sh
          args:
          - -exc
          - |
            export GOPATH=$(pwd)/gopath
            export PATH=$PATH:$(pwd)/gopath/bin/
            env
            find .
            cd gopath/src/github.com/tomkukral/goarchitect/
            ./test.sh
